name: 'Block on release candidates'
description: 'If any sysarb packages uses release candidate versions this action will fail'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - run: node index.js
      shell: bash
